require 'rails_helper'

RSpec.describe Venue, type: :model do
  describe 'associations' do
    it { should belong_to(:owner).class_name('User').with_foreign_key('owner_id') }
    it { should have_many(:venue_operating_hours).dependent(:destroy) }
    it { should have_many(:venue_users).dependent(:destroy) }
    it { should have_many(:staff_members).through(:venue_users).source(:user) }
  end

  describe 'validations' do
    subject { build(:venue, :skip_callbacks) }

    it { should validate_presence_of(:name) }
    # Slug is auto-generated by callback, so presence validation behaves differently
    # it { should validate_presence_of(:slug) }
    it { should validate_presence_of(:address) }
    it { should validate_uniqueness_of(:slug) }

    it 'validates name minimum length' do
      venue = build(:venue, :skip_callbacks, name: 'ab')
      expect(venue).not_to be_valid
      expect(venue.errors[:name]).to include('is too short (minimum is 3 characters)')
    end

    it 'validates name maximum length' do
      venue = build(:venue, :skip_callbacks, name: 'a' * 101)
      expect(venue).not_to be_valid
      expect(venue.errors[:name]).to include('is too long (maximum is 100 characters)')
    end

    it 'validates slug format' do
      venue = build(:venue, :skip_callbacks, slug: 'Invalid Slug!')
      expect(venue).not_to be_valid
      expect(venue.errors[:slug]).to include('only lowercase letters, numbers, and hyphens')
    end

    it 'validates phone number format' do
      venue = build(:venue, :skip_callbacks, phone_number: 'invalid')
      expect(venue).not_to be_valid
      expect(venue.errors[:phone_number]).to be_present
    end

    it 'validates email format' do
      venue = build(:venue, :skip_callbacks, email: 'invalid-email')
      expect(venue).not_to be_valid
      expect(venue.errors[:email]).to be_present
    end

    it 'validates latitude range' do
      venue = build(:venue, :skip_callbacks, latitude: 100)
      expect(venue).not_to be_valid
      expect(venue.errors[:latitude]).to be_present
    end

    it 'validates longitude range' do
      venue = build(:venue, :skip_callbacks, longitude: 200)
      expect(venue).not_to be_valid
      expect(venue.errors[:longitude]).to be_present
    end
  end

  describe 'one venue per owner validation' do
    let(:owner) { create(:user) }

    it 'allows owner to create first venue' do
      venue = build(:venue, owner: owner)
      expect(venue).to be_valid
    end

    it 'prevents owner from creating second venue' do
      create(:venue, owner: owner)
      second_venue = build(:venue, owner: owner)
      expect(second_venue).not_to be_valid
      expect(second_venue.errors[:owner]).to include('can only own one venue in MVP')
    end
  end

  describe 'callbacks' do
    describe 'slug generation' do
      it 'auto-generates slug from name' do
        venue = create(:venue, name: 'My Sports Arena', slug: nil)
        expect(venue.slug).to eq('my-sports-arena')
      end

      it 'handles slug conflicts by adding counter' do
        create(:venue, name: 'Sports Arena', slug: 'sports-arena')
        venue2 = create(:venue, name: 'Sports Arena', slug: nil)
        expect(venue2.slug).to eq('sports-arena-2')
      end

      it 'does not override manually set slug' do
        venue = create(:venue, name: 'Sports Arena', slug: 'custom-slug')
        expect(venue.slug).to eq('custom-slug')
      end
    end
  end

  describe 'scopes' do
    let!(:active_venue) { create(:venue, is_active: true) }
    let!(:inactive_venue) { create(:venue, :inactive) }

    describe '.active' do
      it 'returns only active venues' do
        expect(Venue.active).to include(active_venue)
        expect(Venue.active).not_to include(inactive_venue)
      end
    end

    describe '.inactive' do
      it 'returns only inactive venues' do
        expect(Venue.inactive).to include(inactive_venue)
        expect(Venue.inactive).not_to include(active_venue)
      end
    end

    describe '.in_city' do
      let!(:karachi_venue) { create(:venue, city: 'Karachi') }
      let!(:lahore_venue) { create(:venue, city: 'Lahore') }

      it 'returns venues in specified city' do
        expect(Venue.in_city('Karachi')).to include(karachi_venue)
        expect(Venue.in_city('Karachi')).not_to include(lahore_venue)
      end
    end
  end

  describe 'instance methods' do
    let(:venue) { create(:venue) }
    let!(:operating_hours) do
      # opens from monday to friday, closed on weekends
      (0..4).each do |day|
        create(:venue_operating_hour, venue: venue, day_of_week: day, is_closed: false, opens_at: '09:00', closes_at: '17:00')
      end
      (5..6).each do |day|
        create(:venue_operating_hour, venue: venue, day_of_week: day, is_closed: true)
      end
    end

    describe '#google_maps_url' do
      it 'returns Google Maps URL when coordinates present' do
        venue.update(latitude: 24.8175, longitude: 67.0297)
        expect(venue.google_maps_url).to eq('https://www.google.com/maps?q=24.8175,67.0297')
      end

      it 'returns nil when coordinates missing' do
        venue.update(latitude: nil, longitude: nil)
        expect(venue.google_maps_url).to be_nil
      end
    end

    describe '#activate!' do
      it 'sets is_active to true' do
        venue.update(is_active: false)
        expect { venue.activate! }.to change { venue.is_active }.from(false).to(true)
      end
    end

    describe '#deactivate!' do
      it 'sets is_active to false' do
        expect { venue.deactivate! }.to change { venue.is_active }.from(true).to(false)
      end
    end

    describe '#operating_hours_for' do
      it 'returns operating hours for specified day' do
        monday_hours = venue.operating_hours_for(1)
        expect(monday_hours).to be_present
        expect(monday_hours.day_of_week).to eq(1)
      end
    end

    describe '#open_on?' do
      it 'returns true when venue is open on specified day' do
        expect(venue.open_on?(0)).to be true # Monday
      end

      it 'returns false when venue is closed on specified day' do
        expect(venue.open_on?(5)).to be false # Saturday
      end
    end
  end
end
